# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manav.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1301, 778)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(240, -20, 951, 731))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.ana_page = QtWidgets.QWidget()
        self.ana_page.setObjectName("ana_page")
        self.label = QtWidgets.QLabel(self.ana_page)
        self.label.setGeometry(QtCore.QRect(360, 110, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.calisan_button = QtWidgets.QPushButton(self.ana_page)
        self.calisan_button.setGeometry(QtCore.QRect(529, 340, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.calisan_button.setFont(font)
        self.calisan_button.setStyleSheet("QPushButton {\n"
"border-radius:10px;\n"
"font: 87 8pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(23, 255, 81);\n"
"    border: 0px solid\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.calisan_button.setObjectName("calisan_button")
        self.label_2 = QtWidgets.QLabel(self.ana_page)
        self.label_2.setGeometry(QtCore.QRect(550, 290, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(85, 0, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.musteri_button = QtWidgets.QPushButton(self.ana_page)
        self.musteri_button.setGeometry(QtCore.QRect(282, 340, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.musteri_button.setFont(font)
        self.musteri_button.setStyleSheet("QPushButton {\n"
"border-radius:10px;\n"
"font: 87 8pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(23, 255, 81);\n"
"    border: 0px solid\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.musteri_button.setObjectName("musteri_button")
        self.label_3 = QtWidgets.QLabel(self.ana_page)
        self.label_3.setGeometry(QtCore.QRect(320, 290, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(170, 170, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.ana_page)
        self.label_4.setGeometry(QtCore.QRect(290, 460, 471, 151))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(60)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.label_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.ana_page)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.pushButton_2 = QtWidgets.QPushButton(self.page)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 220, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"border-radius:10px;\n"
"font: 87 8pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(23, 255, 81);\n"
"    border: 0px solid\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(260, 40, 311, 141))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(48, 28, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout.addWidget(self.lineEdit_3)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tabWidget = QtWidgets.QTabWidget(self.page_2)
        self.tabWidget.setGeometry(QtCore.QRect(0, 40, 901, 661))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setTabletTracking(False)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Sebze = QtWidgets.QWidget()
        self.Sebze.setObjectName("Sebze")
        self.tableWidgett = QtWidgets.QTableWidget(self.Sebze)
        self.tableWidgett.setGeometry(QtCore.QRect(180, 160, 671, 371))
        self.tableWidgett.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidgett.setAlternatingRowColors(False)
        self.tableWidgett.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidgett.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidgett.setObjectName("tableWidgett")
        self.tableWidgett.setColumnCount(2)
        self.tableWidgett.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgett.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgett.setHorizontalHeaderItem(1, item)
        self.sebze_table_linee = QtWidgets.QLineEdit(self.Sebze)
        self.sebze_table_linee.setGeometry(QtCore.QRect(120, 91, 113, 20))
        self.sebze_table_linee.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sebze_table_linee.setObjectName("sebze_table_linee")
        self.sebze_kilo_linee = QtWidgets.QLineEdit(self.Sebze)
        self.sebze_kilo_linee.setGeometry(QtCore.QRect(550, 70, 113, 20))
        self.sebze_kilo_linee.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sebze_kilo_linee.setObjectName("sebze_kilo_linee")
        self.sebze_linee = QtWidgets.QLineEdit(self.Sebze)
        self.sebze_linee.setGeometry(QtCore.QRect(550, 32, 113, 20))
        self.sebze_linee.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sebze_linee.setObjectName("sebze_linee")
        self.label_23 = QtWidgets.QLabel(self.Sebze)
        self.label_23.setGeometry(QtCore.QRect(440, 30, 101, 21))
        self.label_23.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.Sebze)
        self.label_24.setGeometry(QtCore.QRect(440, 70, 101, 21))
        self.label_24.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.kilo_table_linee = QtWidgets.QLineEdit(self.Sebze)
        self.kilo_table_linee.setGeometry(QtCore.QRect(120, 131, 113, 20))
        self.kilo_table_linee.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.kilo_table_linee.setObjectName("kilo_table_linee")
        self.label_25 = QtWidgets.QLabel(self.Sebze)
        self.label_25.setGeometry(QtCore.QRect(10, 90, 101, 21))
        self.label_25.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.Sebze)
        self.label_26.setGeometry(QtCore.QRect(10, 130, 101, 21))
        self.label_26.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.sebze_kilo_buttonn = QtWidgets.QPushButton(self.Sebze)
        self.sebze_kilo_buttonn.setGeometry(QtCore.QRect(690, 38, 131, 51))
        self.sebze_kilo_buttonn.setStyleSheet("QPushButton {\n"
"border-radius:10px;\n"
"font: 87 8pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(23, 255, 81);\n"
"    border: 0px solid\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 255, 0);\n"
"\n"
"}")
        self.sebze_kilo_buttonn.setObjectName("sebze_kilo_buttonn")
        self.sebze_kilo_table_refreshh = QtWidgets.QPushButton(self.Sebze)
        self.sebze_kilo_table_refreshh.setGeometry(QtCore.QRect(420, 540, 151, 61))
        self.sebze_kilo_table_refreshh.setStyleSheet("QPushButton {\n"
"border-radius:10px;\n"
"font: 87 8pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(23, 255, 81);\n"
"    border: 0px solid\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 255, 255);\n"
"\n"
"}")
        self.sebze_kilo_table_refreshh.setObjectName("sebze_kilo_table_refreshh")
        self.sebze_guncellee = QtWidgets.QPushButton(self.Sebze)
        self.sebze_guncellee.setGeometry(QtCore.QRect(30, 180, 121, 51))
        self.sebze_guncellee.setStyleSheet("QPushButton {\n"
"border-radius:10px;\n"
"font: 87 8pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(23, 255, 81);\n"
"    border: 0px solid\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 255, 255);\n"
"\n"
"}")
        self.sebze_guncellee.setObjectName("sebze_guncellee")
        self.pushButton_8 = QtWidgets.QPushButton(self.Sebze)
        self.pushButton_8.setGeometry(QtCore.QRect(30, 260, 121, 51))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"border-radius:10px;\n"
"font: 87 8pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(23, 255, 81);\n"
"    border: 0px solid\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/iconlar/sebze.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Sebze, icon, "")
        self.Meyve = QtWidgets.QWidget()
        self.Meyve.setObjectName("Meyve")
        self.tableWidgett_2 = QtWidgets.QTableWidget(self.Meyve)
        self.tableWidgett_2.setGeometry(QtCore.QRect(180, 160, 671, 371))
        self.tableWidgett_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidgett_2.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidgett_2.setObjectName("tableWidgett_2")
        self.tableWidgett_2.setColumnCount(2)
        self.tableWidgett_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgett_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgett_2.setHorizontalHeaderItem(1, item)
        self.meyve_table_refresh = QtWidgets.QPushButton(self.Meyve)
        self.meyve_table_refresh.setGeometry(QtCore.QRect(420, 540, 151, 61))
        self.meyve_table_refresh.setStyleSheet("QPushButton {\n"
"border-radius:10px;\n"
"font: 87 8pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(23, 255, 81);\n"
"    border: 0px solid\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 255, 255);\n"
"\n"
"}")
        self.meyve_table_refresh.setObjectName("meyve_table_refresh")
        self.label_27 = QtWidgets.QLabel(self.Meyve)
        self.label_27.setGeometry(QtCore.QRect(10, 90, 101, 21))
        self.label_27.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.meyve_table_line = QtWidgets.QLineEdit(self.Meyve)
        self.meyve_table_line.setGeometry(QtCore.QRect(120, 91, 113, 20))
        self.meyve_table_line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.meyve_table_line.setObjectName("meyve_table_line")
        self.label_28 = QtWidgets.QLabel(self.Meyve)
        self.label_28.setGeometry(QtCore.QRect(10, 130, 101, 21))
        self.label_28.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.meyve_kilo_line = QtWidgets.QLineEdit(self.Meyve)
        self.meyve_kilo_line.setGeometry(QtCore.QRect(120, 131, 113, 20))
        self.meyve_kilo_line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.meyve_kilo_line.setObjectName("meyve_kilo_line")
        self.label_29 = QtWidgets.QLabel(self.Meyve)
        self.label_29.setGeometry(QtCore.QRect(440, 30, 101, 21))
        self.label_29.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.sebze_guncellee_2 = QtWidgets.QPushButton(self.Meyve)
        self.sebze_guncellee_2.setGeometry(QtCore.QRect(30, 180, 121, 51))
        self.sebze_guncellee_2.setStyleSheet("QPushButton {\n"
"border-radius:10px;\n"
"font: 87 8pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(23, 255, 81);\n"
"    border: 0px solid\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 255, 255);\n"
"\n"
"}")
        self.sebze_guncellee_2.setObjectName("sebze_guncellee_2")
        self.pushButton_9 = QtWidgets.QPushButton(self.Meyve)
        self.pushButton_9.setGeometry(QtCore.QRect(30, 260, 121, 51))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"border-radius:10px;\n"
"font: 87 8pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(23, 255, 81);\n"
"    border: 0px solid\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_30 = QtWidgets.QLabel(self.Meyve)
        self.label_30.setGeometry(QtCore.QRect(440, 70, 101, 21))
        self.label_30.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.meyve_line = QtWidgets.QLineEdit(self.Meyve)
        self.meyve_line.setGeometry(QtCore.QRect(550, 32, 113, 20))
        self.meyve_line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.meyve_line.setPlaceholderText("")
        self.meyve_line.setObjectName("meyve_line")
        self.meyve_kilo = QtWidgets.QLineEdit(self.Meyve)
        self.meyve_kilo.setGeometry(QtCore.QRect(550, 70, 113, 20))
        self.meyve_kilo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.meyve_kilo.setObjectName("meyve_kilo")
        self.meyve_kaydet = QtWidgets.QPushButton(self.Meyve)
        self.meyve_kaydet.setGeometry(QtCore.QRect(690, 38, 131, 51))
        self.meyve_kaydet.setStyleSheet("QPushButton {\n"
"border-radius:10px;\n"
"font: 87 8pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(23, 255, 81);\n"
"    border: 0px solid\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 255, 0);\n"
"\n"
"}")
        self.meyve_kaydet.setObjectName("meyve_kaydet")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/iconlar/meyvee.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Meyve, icon1, "")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(270, 150, 471, 291))
        self.label_6.setStyleSheet("background-color:rgba(66,64,66,0.7);border-radius:20px\n"
"")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page_3)
        self.label_7.setGeometry(QtCore.QRect(420, 160, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.giris_kullanici_line = QtWidgets.QLineEdit(self.page_3)
        self.giris_kullanici_line.setGeometry(QtCore.QRect(460, 230, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.giris_kullanici_line.setFont(font)
        self.giris_kullanici_line.setStyleSheet("background-color:rgb(29,37,97);\n"
"border:none;\n"
"border-radius:15px;\n"
"color:white;\n"
"padding-left:20px;\n"
"padding-right:20px\n"
"")
        self.giris_kullanici_line.setObjectName("giris_kullanici_line")
        self.giris_sifre_line = QtWidgets.QLineEdit(self.page_3)
        self.giris_sifre_line.setGeometry(QtCore.QRect(460, 280, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.giris_sifre_line.setFont(font)
        self.giris_sifre_line.setStyleSheet("background-color:rgb(29,37,97);\n"
"border:none;\n"
"border-radius:15px;\n"
"color:white;\n"
"padding-left:20px;\n"
"padding-right:20px\n"
"")
        self.giris_sifre_line.setObjectName("giris_sifre_line")
        self.label_8 = QtWidgets.QLabel(self.page_3)
        self.label_8.setGeometry(QtCore.QRect(290, 220, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.page_3)
        self.label_9.setGeometry(QtCore.QRect(290, 290, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 370, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{color: rgb(255, 255, 255);\n"
"background-color:rgb(82,84,99);\n"
"border:none;\n"
"border-radius:20px;}\n"
"\n"
"QPushButton::hover{background-color:black;}\n"
"QPushButton::focus{background-color:green;}\n"
"\n"
" ")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_4.setGeometry(QtCore.QRect(580, 370, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(13)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{color: rgb(255, 255, 255);\n"
"background-color:rgb(82,84,99);\n"
"border:none;\n"
"border-radius:20px;}\n"
"\n"
"QPushButton::hover{background-color:black;}\n"
"QPushButton::focus{background-color:green;}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.formLayoutWidget = QtWidgets.QWidget(self.page_4)
        self.formLayoutWidget.setGeometry(QtCore.QRect(150, 40, 370, 599))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setVerticalSpacing(30)
        self.formLayout.setObjectName("formLayout")
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.isim_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.isim_line.setFont(font)
        self.isim_line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.isim_line.setObjectName("isim_line")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.isim_line)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.soyisim_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.soyisim_line.setFont(font)
        self.soyisim_line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.soyisim_line.setObjectName("soyisim_line")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.soyisim_line)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.kullanici_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.kullanici_line.setFont(font)
        self.kullanici_line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.kullanici_line.setObjectName("kullanici_line")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.kullanici_line)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.sifre_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre_line.setFont(font)
        self.sifre_line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sifre_line.setObjectName("sifre_line")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sifre_line)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.tc_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tc_line.setFont(font)
        self.tc_line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tc_line.setObjectName("tc_line")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.tc_line)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.tel_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tel_line.setFont(font)
        self.tel_line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tel_line.setObjectName("tel_line")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.tel_line)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.eposta_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.eposta_line.setFont(font)
        self.eposta_line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.eposta_line.setObjectName("eposta_line")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.eposta_line)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.dogum_dateedit = QtWidgets.QDateEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dogum_dateedit.setFont(font)
        self.dogum_dateedit.setAcceptDrops(False)
        self.dogum_dateedit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dogum_dateedit.setDateTime(QtCore.QDateTime(QtCore.QDate(2007, 1, 1), QtCore.QTime(23, 59, 59)))
        self.dogum_dateedit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2007, 1, 1), QtCore.QTime(23, 59, 59)))
        self.dogum_dateedit.setMaximumDate(QtCore.QDate(2007, 1, 1))
        self.dogum_dateedit.setMinimumDate(QtCore.QDate(1933, 1, 1))
        self.dogum_dateedit.setCalendarPopup(True)
        self.dogum_dateedit.setObjectName("dogum_dateedit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.dogum_dateedit)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.label_17)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.adres_text = QtWidgets.QTextEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.adres_text.setFont(font)
        self.adres_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.adres_text.setObjectName("adres_text")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.adres_text)
        self.kayit_ol_button = QtWidgets.QPushButton(self.page_4)
        self.kayit_ol_button.setGeometry(QtCore.QRect(400, 660, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.kayit_ol_button.setFont(font)
        self.kayit_ol_button.setStyleSheet("QPushButton{color: rgb(255, 255, 255);\n"
"background-color:rgb(82,84,99);\n"
"border:none;\n"
"border-radius:20px;}\n"
"\n"
"QPushButton::hover{background-color:black;}\n"
"QPushButton::focus{background-color:green;}")
        self.kayit_ol_button.setObjectName("kayit_ol_button")
        self.geri_git_button = QtWidgets.QPushButton(self.page_4)
        self.geri_git_button.setGeometry(QtCore.QRect(150, 660, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.geri_git_button.setFont(font)
        self.geri_git_button.setStyleSheet("QPushButton{color: rgb(255, 255, 255);\n"
"background-color:rgb(82,84,99);\n"
"border:none;\n"
"border-radius:20px;}\n"
"\n"
"QPushButton::hover{background-color:red;}\n"
"QPushButton::focus{background-color:green;}")
        self.geri_git_button.setObjectName("geri_git_button")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_21 = QtWidgets.QLabel(self.page_5)
        self.label_21.setGeometry(QtCore.QRect(720, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.page_5)
        self.label_22.setGeometry(QtCore.QRect(720, 70, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_22.setText("")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_31 = QtWidgets.QLabel(self.page_5)
        self.label_31.setGeometry(QtCore.QRect(680, 130, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_5.setGeometry(QtCore.QRect(730, 190, 101, 51))
        self.pushButton_5.setStyleSheet("QPushButton{color: rgb(255, 255, 255);\n"
"background-color:rgb(82,84,99);\n"
"border:none;\n"
"border-radius:20px;}\n"
"\n"
"QPushButton::hover{background-color:black;}\n"
"QPushButton::focus{background-color:green;}\n"
"\n"
" ")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_6.setGeometry(QtCore.QRect(730, 260, 101, 51))
        self.pushButton_6.setStyleSheet("QPushButton{color: rgb(255, 255, 255);\n"
"background-color:rgb(82,84,99);\n"
"border:none;\n"
"border-radius:20px;}\n"
"\n"
"QPushButton::hover{background-color:black;}\n"
"QPushButton::focus{background-color:green;}\n"
"\n"
" ")
        self.pushButton_6.setObjectName("pushButton_6")
        self.stackedWidget.addWidget(self.page_5)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 60, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"border-radius:10px;\n"
"font: 87 8pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(23, 255, 81);\n"
"    border: 0px solid\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 0, 0);\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1301, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(1)
        self.comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Manavımıza Hoş Geldiniz"))
        self.calisan_button.setText(_translate("MainWindow", "TIKLA"))
        self.label_2.setText(_translate("MainWindow", "Çalışan Girişi"))
        self.musteri_button.setText(_translate("MainWindow", "TIKLA"))
        self.label_3.setText(_translate("MainWindow", "Müşteri Girişi"))
        self.pushButton_2.setText(_translate("MainWindow", "GİRİŞ"))
        self.label_5.setText(_translate("MainWindow", "Şifre:"))
        self.tableWidgett.setSortingEnabled(True)
        item = self.tableWidgett.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sebze"))
        item = self.tableWidgett.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Kilo"))
        self.label_23.setText(_translate("MainWindow", "Sebze"))
        self.label_24.setText(_translate("MainWindow", "Kilo"))
        self.label_25.setText(_translate("MainWindow", "Sebze"))
        self.label_26.setText(_translate("MainWindow", "Kilo"))
        self.sebze_kilo_buttonn.setText(_translate("MainWindow", "Kaydet"))
        self.sebze_kilo_table_refreshh.setText(_translate("MainWindow", "Refresh"))
        self.sebze_guncellee.setText(_translate("MainWindow", "Güncelle"))
        self.pushButton_8.setText(_translate("MainWindow", "Sil"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Sebze), _translate("MainWindow", "Sebze"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.Sebze), _translate("MainWindow", "Sebze Alanı"))
        self.tableWidgett_2.setSortingEnabled(True)
        item = self.tableWidgett_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Meyve"))
        item = self.tableWidgett_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Kilo"))
        self.meyve_table_refresh.setText(_translate("MainWindow", "Refresh"))
        self.label_27.setText(_translate("MainWindow", "Meyve"))
        self.label_28.setText(_translate("MainWindow", "Kilo"))
        self.label_29.setText(_translate("MainWindow", "Meyve"))
        self.sebze_guncellee_2.setText(_translate("MainWindow", "Güncelle"))
        self.pushButton_9.setText(_translate("MainWindow", "Sil"))
        self.label_30.setText(_translate("MainWindow", "Kilo"))
        self.meyve_kaydet.setText(_translate("MainWindow", "Kaydet"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Meyve), _translate("MainWindow", "Meyve"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.Meyve), _translate("MainWindow", "Meyve Alanı"))
        self.label_7.setText(_translate("MainWindow", "LOGİN THE SYSTEM"))
        self.label_8.setText(_translate("MainWindow", "Kullanıcı adı:"))
        self.label_9.setText(_translate("MainWindow", "Şifre:"))
        self.pushButton_3.setText(_translate("MainWindow", "Giriş"))
        self.pushButton_4.setText(_translate("MainWindow", "Kayıt Ol"))
        self.label_10.setText(_translate("MainWindow", "İsim:"))
        self.label_11.setText(_translate("MainWindow", "Soyisim:"))
        self.label_18.setText(_translate("MainWindow", "Kullanıcı adı:"))
        self.label_19.setText(_translate("MainWindow", "Şifre:"))
        self.label_13.setText(_translate("MainWindow", "Tc Kimlik:"))
        self.label_20.setText(_translate("MainWindow", "Cinsiyet:"))
        self.label_15.setText(_translate("MainWindow", "Telefon:"))
        self.label_16.setText(_translate("MainWindow", "E-posta:"))
        self.label_12.setText(_translate("MainWindow", "Doğum yılı:"))
        self.label_14.setText(_translate("MainWindow", "Adres:"))
        self.label_17.setText(_translate("MainWindow", "Kayıt olarak Gizlilik İlkeleri\'ni ve\n"
" Hizmet Şartları\'nı kabul etmiş olursunuz"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Erkek"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Kadın"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Belirtmemeyi Tercih Ediyorum"))
        self.adres_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.kayit_ol_button.setText(_translate("MainWindow", "Kayıt ol"))
        self.geri_git_button.setText(_translate("MainWindow", "Geri Git"))
        self.label_21.setText(_translate("MainWindow", "Hoşgeldin"))
        self.label_31.setText(_translate("MainWindow", "Ne almak istersin?"))
        self.pushButton_5.setText(_translate("MainWindow", "Sebze"))
        self.pushButton_6.setText(_translate("MainWindow", "Meyve"))
        self.pushButton.setText(_translate("MainWindow", "ANA SAYFA"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
import ortakresim_rc
